---
name: 'hooks-workflow'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.8
  NODE_VERSION: 14

jobs:
  tests:
    name: 'tests'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements-dev.txt

      - name: Run tests
        run: pytest -vv

  semantic-release:
    name: 'semantic release'
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - tests
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.3
            @semantic-release/changelog@5.0.1
            @semantic-release/github@7.2.3
            @semantic-release/git@9.0.0
            @semantic-release/exec@5.0.0
            @semantic-release/npm@7.0.5
            conventional-changelog-conventionalcommits@4.3.0
